server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://blindboxsystem.crcuqosss46w.ap-southeast-1.rds.amazonaws.com:3306/blindboxsystem
    username: admin
    password: khoa2486
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  jwt:
    secretKey: 85br1PWiVMiDqYllgMB7XZBdVb90sBy7DjsLFl08wsbC12yTF2W0KMX/pHIPU+T28uXuNw/fGu5P/nxncsaNEA==
    accessTokenExpirationTime: 172800000 # 2 days
